{{- if .Values.secrets.externalSecret.enabled -}}
{{- $secretStoreRef := required "secrets.externalSecret.secretStoreRef is required when externalSecret is enabled" .Values.secrets.externalSecret.secretStoreRef -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ghillie.fullname" . }}
  labels:
    {{- include "ghillie.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $secretStoreRef }}
    kind: {{ .Values.secrets.externalSecret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "ghillie.fullname" . }}
  {{- with .Values.secrets.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
